### ISSUE TITLE
Hidden posts somehow become visible again

### ISSUE THREAD

**Issue by newtover** [pepyatka/pepyatka-server#206] opened 2015-05-07 08:16 UTC
Not sure if this happens of the first page, but it can be easily reproduced on the second page:

1. go to https://freefeed.net/?offset=25
2. hide some post with comments (the post becomes hidden, hidden post count is incremented)
3. refresh the page

result: the post is displayed again, the hidden post count is decremented back
expected: the post should be hidden

**Comment by epicmonkey** [comment] 2015-05-18 23:29
This might be resolved in https://github.com/pepyatka/pepyatka-server/commit/1b5b673

**Comment by epicmonkey** [comment] 2015-05-29 15:17
@smallq-git I wonder if it's any better now?

**Comment by smallq-git** [comment] 2015-05-30 02:52
I actually never saw this myself, so need to ask users.

**Comment by berkus** [comment] 2015-05-30 08:43
qub writes:
воспроизводится. автор пишет комментарий, запись видна снова.

**Comment by smallq-git** [comment] 2015-05-30 20:30
And yet I was unable to reproduce it on test server. I edited the post, commented, edited comments as both author, subscriber and third-party user - post stubbornly remained hidden.

I think we need to establish if the post is:
- made by someone you're subscribed to, someone your friends are subscribed to or 3rd party;
- liked by you, your friends or author;
- commented by you, your friends or author;
- edited by author;
- has comments edited or deleted;
- unliked by someone.

I suspect it's a combination of several factors but I can't hit upon it :(

**Comment by epicmonkey** [comment] 2015-06-04 17:12
Closing. If anything comes up, let's create a new story.

**Closed by epicmonkey** 2015-06-04 17:12 UTC
Labels: blocker, bug
